// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKOwVn5aG8dFKsOGNqHCwVmU0Cs-AX6VE',
    appId: '1:145730313552:web:f5991f50e99d285501a055',
    messagingSenderId: '145730313552',
    projectId: 'shopoes-2e0b8',
    authDomain: 'shopoes-2e0b8.firebaseapp.com',
    storageBucket: 'shopoes-2e0b8.appspot.com',
    measurementId: 'G-74HZ7S3K16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDznM1m62LdnnVIGLQcF5YPu64nuSJHN6M',
    appId: '1:145730313552:android:55ea23695f29b29901a055',
    messagingSenderId: '145730313552',
    projectId: 'shopoes-2e0b8',
    storageBucket: 'shopoes-2e0b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBF4BZPSrJ-zX-AYD899n6NkQYaNKq-Zo',
    appId: '1:145730313552:ios:bcaeaa1d20151d0601a055',
    messagingSenderId: '145730313552',
    projectId: 'shopoes-2e0b8',
    storageBucket: 'shopoes-2e0b8.appspot.com',
    iosBundleId: 'com.example.ecommerceShop',
  );
}
